# # by Julian

import random
import pymysql

# Database password
mdpbd = "VUpitdBD"
print("gfssd")
# Connect to the database
try:
    conn = pymysql.connect(host='cigale1.lescigales.org', port=3310, user='s4a_julian', password=mdpbd, database='s4a_julian', charset='utf8')
    # For local connection, use the following line and comment out the above line
    # conn = pymysql.connect(host='localhost', user='root', password='mdpbd', database='saejava')
    cursor = conn.cursor()
    print("Database connection successful.")
except pymysql.MySQLError as e:
    print(f"Error connecting to the database: {e}")
    exit(1)

# Mapping of country names to ISO 3166-1 alpha-2 country codes
country_codes_fr = {
    'Afghanistan': 'af',
    'Albanie': 'al',
    'Algerie': 'dz',
    'Andorre': 'ad',
    'Angola': 'ao',
    'Antigua-et-Barbuda': 'ag',
    'Argentine': 'ar',
    'Armenie': 'am',
    'Australie': 'au',
    'Autriche': 'at',
    'Azerbaidjan': 'az',
    'Bahamas': 'bs',
    'Bahrein': 'bh',
    'Bangladesh': 'bd',
    'Barbade': 'bb',
    'Belarus': 'by',
    'Belgique': 'be',
    'Belize': 'bz',
    'Benin': 'bj',
    'Bhoutan': 'bt',
    'Bolivie': 'bo',
    'Bosnie-Herzegovine': 'ba',
    'Botswana': 'bw',
    'Bresil': 'br',
    'Brunei': 'bn',
    'Bulgarie': 'bg',
    'Burkina Faso': 'bf',
    'Burundi': 'bi',
    'Cabo Verde': 'cv',
    'Cambodge': 'kh',
    'Cameroun': 'cm',
    'Canada': 'ca',
    'Republique centrafricaine': 'cf',
    'Tchad': 'td',
    'Chili': 'cl',
    'Chine': 'cn',
    'Colombie': 'co',
    'Comores': 'km',
    'Republique democratique du Congo': 'cd',
    'Republique du Congo': 'cg',
    'Costa Rica': 'cr',
    'Croatie': 'hr',
    'Cuba': 'cu',
    'Chypre': 'cy',
    'Republique tchèque': 'cz',
    'Danemark': 'dk',
    'Djibouti': 'dj',
    'Dominique': 'dm',
    'Republique dominicaine': 'do',
    'equateur': 'ec',
    'egypte': 'eg',
    'El Salvador': 'sv',
    'Guinee equatoriale': 'gq',
    'erythree': 'er',
    'Estonie': 'ee',
    'Eswatini': 'sz',
    'ethiopie': 'et',
    'Fidji': 'fj',
    'Finlande': 'fi',
    'France': 'fr',
    'Gabon': 'ga',
    'Gambie': 'gm',
    'Georgie': 'ge',
    'Allemagne': 'de',
    'Ghana': 'gh',
    'Grèce': 'gr',
    'Grenade': 'gd',
    'Guatemala': 'gt',
    'Guinee': 'gn',
    'Guinee-Bissau': 'gw',
    'Guyana': 'gy',
    'Haiti': 'ht',
    'Honduras': 'hn',
    'Hongrie': 'hu',
    'Islande': 'is',
    'Inde': 'in',
    'Indonesie': 'id',
    'Iran': 'ir',
    'Irak': 'iq',
    'Irlande': 'ie',
    'Israel': 'il',
    'Italie': 'it',
    'Jamaique': 'jm',
    'Japon': 'jp',
    'Jordanie': 'jo',
    'Kazakhstan': 'kz',
    'Kenya': 'ke',
    'Kiribati': 'ki',
    'Coree du Nord': 'kp',
    'Coree du Sud': 'kr',
    'Kosovo': 'xk',
    'Koweit': 'kw',
    'Kirghizistan': 'kg',
    'Laos': 'la',
    'Lettonie': 'lv',
    'Liban': 'lb',
    'Lesotho': 'ls',
    'Liberia': 'lr',
    'Libye': 'ly',
    'Liechtenstein': 'li',
    'Lituanie': 'lt',
    'Luxembourg': 'lu',
    'Madagascar': 'mg',
    'Malawi': 'mw',
    'Malaisie': 'my',
    'Maldives': 'mv',
    'Mali': 'ml',
    'Malte': 'mt',
    'Îles Marshall': 'mh',
    'Mauritanie': 'mr',
    'Maurice': 'mu',
    'Mexique': 'mx',
    'Micronesie': 'fm',
    'Moldavie': 'md',
    'Monaco': 'mc',
    'Mongolie': 'mn',
    'Montenegro': 'me',
    'Maroc': 'ma',
    'Mozambique': 'mz',
    'Myanmar': 'mm',
    'Namibie': 'na',
    'Nauru': 'nr',
    'Nepal': 'np',
    'Pays-Bas': 'nl',
    'Nouvelle-Zelande': 'nz',
    'Nicaragua': 'ni',
    'Niger': 'ne',
    'Nigeria': 'ng',
    'Macedoine du Nord': 'mk',
    'Norvège': 'no',
    'Oman': 'om',
    'Pakistan': 'pk',
    'Palaos': 'pw',
    'Palestine': 'ps',
    'Panama': 'pa',
    'Papouasie-Nouvelle-Guinee': 'pg',
    'Paraguay': 'py',
    'Perou': 'pe',
    'Philippines': 'ph',
    'Pologne': 'pl',
    'Portugal': 'pt',
    'Qatar': 'qa',
    'Roumanie': 'ro',
    'Russie': 'ru',
    'Rwanda': 'rw',
    'Saint-Christophe-et-Nievès': 'kn',
    'Sainte-Lucie': 'lc',
    'Saint-Vincent-et-les-Grenadines': 'vc',
    'Samoa': 'ws',
    'Saint-Marin': 'sm',
    'Sao Tome-et-Principe': 'st',
    'Arabie saoudite': 'sa',
    'Senegal': 'sn',
    'Serbie': 'rs',
    'Seychelles': 'sc',
    'Sierra Leone': 'sl',
    'Singapour': 'sg',
    'Slovaquie': 'sk',
    'Slovenie': 'si',
    'Îles Salomon': 'sb',
    'Somalie': 'so',
    'Afrique du Sud': 'za',
    'Soudan du Sud': 'ss',
    'Espagne': 'es',
    'Sri Lanka': 'lk',
    'Soudan': 'sd',
    'Suriname': 'sr',
    'Suède': 'se',
    'Suisse': 'ch',
    'Syrie': 'sy',
    'Taiwan': 'tw',
    'Tadjikistan': 'tj',
    'Tanzanie': 'tz',
    'Thailande': 'th',
    'Timor oriental': 'tl',
    'Togo': 'tg',
    'Tonga': 'to',
    'Trinite-et-Tobago': 'tt',
    'Tunisie': 'tn',
    'Turquie': 'tr',
    'Turkmenistan': 'tm',
    'Tuvalu': 'tv',
    'Ouganda': 'ug',
    'Ukraine': 'ua',
    'emirats arabes unis': 'ae',
    'Royaume-Uni': 'gb',
    'etats-Unis': 'us',
    'Uruguay': 'uy',
    'Ouzbekistan': 'uz',
    'Vanuatu': 'vu',
    'Vatican': 'va',
    'Venezuela': 've',
    'Viêt Nam': 'vn',
    'Yemen': 'ye',
    'Zambie': 'zm',
    'Zimbabwe': 'zw'
}
country_codes_en = {
    'Afghanistan': 'af',
    'Albania': 'al',
    'Algeria': 'dz',
    'Andorra': 'ad',
    'Angola': 'ao',
    'Antigua and Barbuda': 'ag',
    'Argentina': 'ar',
    'Armenia': 'am',
    'Australia': 'au',
    'Austria': 'at',
    'Azerbaijan': 'az',
    'Bahamas': 'bs',
    'Bahrain': 'bh',
    'Bangladesh': 'bd',
    'Barbados': 'bb',
    'Belarus': 'by',
    'Belgium': 'be',
    'Belize': 'bz',
    'Benin': 'bj',
    'Bhutan': 'bt',
    'Bolivia': 'bo',
    'Bosnia and Herzegovina': 'ba',
    'Botswana': 'bw',
    'Brazil': 'br',
    'Brunei': 'bn',
    'Bulgaria': 'bg',
    'Burkina Faso': 'bf',
    'Burundi': 'bi',
    'Cabo Verde': 'cv',
    'Cambodia': 'kh',
    'Cameroon': 'cm',
    'Canada': 'ca',
    'Central African Republic': 'cf',
    'Chad': 'td',
    'Chile': 'cl',
    'China': 'cn',
    'Colombia': 'co',
    'Comoros': 'km',
    'Congo, Democratic Republic of the': 'cd',
    'Congo, Republic of the': 'cg',
    'Costa Rica': 'cr',
    'Croatia': 'hr',
    'Cuba': 'cu',
    'Cyprus': 'cy',
    'Czech Republic': 'cz',
    'Denmark': 'dk',
    'Djibouti': 'dj',
    'Dominica': 'dm',
    'Dominican Republic': 'do',
    'Ecuador': 'ec',
    'Egypt': 'eg',
    'El Salvador': 'sv',
    'Equatorial Guinea': 'gq',
    'Eritrea': 'er',
    'Estonia': 'ee',
    'Eswatini': 'sz',
    'Ethiopia': 'et',
    'Fiji': 'fj',
    'Finland': 'fi',
    'France': 'fr',
    'Gabon': 'ga',
    'Gambia': 'gm',
    'Georgia': 'ge',
    'Germany': 'de',
    'Ghana': 'gh',
    'Greece': 'gr',
    'Grenada': 'gd',
    'Guatemala': 'gt',
    'Guinea': 'gn',
    'Guinea-Bissau': 'gw',
    'Guyana': 'gy',
    'Haiti': 'ht',
    'Honduras': 'hn',
    'Hungary': 'hu',
    'Iceland': 'is',
    'India': 'in',
    'Indonesia': 'id',
    'Iran': 'ir',
    'Iraq': 'iq',
    'Ireland': 'ie',
    'Israel': 'il',
    'Italy': 'it',
    'Jamaica': 'jm',
    'Japan': 'jp',
    'Jordan': 'jo',
    'Kazakhstan': 'kz',
    'Kenya': 'ke',
    'Kiribati': 'ki',
    'Korea, North': 'kp',
    'Korea, South': 'kr',
    'Kosovo': 'xk',
    'Kuwait': 'kw',
    'Kyrgyzstan': 'kg',
    'Laos': 'la',
    'Latvia': 'lv',
    'Lebanon': 'lb',
    'Lesotho': 'ls',
    'Liberia': 'lr',
    'Libya': 'ly',
    'Liechtenstein': 'li',
    'Lithuania': 'lt',
    'Luxembourg': 'lu',
    'Madagascar': 'mg',
    'Malawi': 'mw',
    'Malaysia': 'my',
    'Maldives': 'mv',
    'Mali': 'ml',
    'Malta': 'mt',
    'Marshall Islands': 'mh',
    'Mauritania': 'mr',
    'Mauritius': 'mu',
    'Mexico': 'mx',
    'Micronesia': 'fm',
    'Moldova': 'md',
    'Monaco': 'mc',
    'Mongolia': 'mn',
    'Montenegro': 'me',
    'Morocco': 'ma',
    'Mozambique': 'mz',
    'Myanmar': 'mm',
    'Namibia': 'na',
    'Nauru': 'nr',
    'Nepal': 'np',
    'Netherlands': 'nl',
    'New Zealand': 'nz',
    'Nicaragua': 'ni',
    'Niger': 'ne',
    'Nigeria': 'ng',
    'North Macedonia': 'mk',
    'Norway': 'no',
    'Oman': 'om',
    'Pakistan': 'pk',
    'Palau': 'pw',
    'Palestine': 'ps',
    'Panama': 'pa',
    'Papua New Guinea': 'pg',
    'Paraguay': 'py',
    'Peru': 'pe',
    'Philippines': 'ph',
    'Poland': 'pl',
    'Portugal': 'pt',
    'Qatar': 'qa',
    'Romania': 'ro',
    'Russia': 'ru',
    'Rwanda': 'rw',
    'Saint Kitts and Nevis': 'kn',
    'Saint Lucia': 'lc',
    'Saint Vincent and the Grenadines': 'vc',
    'Samoa': 'ws',
    'San Marino': 'sm',
    'Sao Tome and Principe': 'st',
    'Saudi Arabia': 'sa',
    'Senegal': 'sn',
    'Serbia': 'rs',
    'Seychelles': 'sc',
    'Sierra Leone': 'sl',
    'Singapore': 'sg',
    'Slovakia': 'sk',
    'Slovenia': 'si',
    'Solomon Islands': 'sb',
    'Somalia': 'so',
    'South Africa': 'za',
    'South Sudan': 'ss',
    'Spain': 'es',
    'Sri Lanka': 'lk',
    'Sudan': 'sd',
    'Suriname': 'sr',
    'Sweden': 'se',
    'Switzerland': 'ch',
    'Syria': 'sy',
    'Taiwan': 'tw',
    'Tajikistan': 'tj',
    'Tanzania': 'tz',
    'Thailand': 'th',
    'Timor-Leste': 'tl',
    'Togo': 'tg',
    'Tonga': 'to',
    'Trinidad and Tobago': 'tt',
    'Tunisia': 'tn',
    'Turkey': 'tr',
    'Turkmenistan': 'tm',
    'Tuvalu': 'tv',
    'Uganda': 'ug',
    'Ukraine': 'ua',
    'United Arab Emirates': 'ae',
    'United Kingdom': 'gb',
    'United States': 'us',
    'Uruguay': 'uy',
    'Uzbekistan': 'uz',
    'Vanuatu': 'vu',
    'Vatican City': 'va',
    'Venezuela': 've',
    'Vietnam': 'vn',
    'Yemen': 'ye',
    'Zambia': 'zm',
    'Zimbabwe': 'zw'
}

try:
    cursor.execute("TRUNCATE `DRAPEAU` ;")

    # Insert data into the database
    for country, code in country_codes_en.items():
        flag_url = f"img/{code.lower()}.png"
        print(f"Inserting: {country} -> {flag_url}")
        # cursor.execute("INSERT INTO DRAPEAU (nomPays, pathImg) VALUES (%s, %s)", (country, flag_url))
        cursor.execute("UPDATE DRAPEAU SET pathImg = %s WHERE nomPays = %s", (flag_url, country))

    conn.commit()
    print("successfully EN.")

        # Insert data into the database
    for country, code in country_codes_fr.items():
        if country not in country_codes_en.keys():
            flag_url = f"img/{code.lower()}.png"
            print(f"Inserting: {country} -> {flag_url}")
            # cursor.execute("INSERT INTO DRAPEAU (nomPays, pathImg) VALUES (%s, %s)", (country, flag_url))
            cursor.execute("UPDATE DRAPEAU SET pathImg = %s WHERE nomPays = %s", (flag_url, country))

    conn.commit()
    print("successfully FR.")
except pymysql.MySQLError as e:
    print(f"Error exe : {e}")

cursor.close()
conn.close()
print("Database deconnecter.")
