-- DROP TABLE IF EXISTS EST_CONSTITUER;
-- DROP TABLE IF EXISTS PARTICIPER_ATHLETE;
-- DROP TABLE IF EXISTS PARTICIPER_EQUIPE;
-- DROP TABLE IF EXISTS EQUIPE;
-- DROP TABLE IF EXISTS MATCH;
-- DROP TABLE IF EXISTS EPREUVE;
-- DROP TABLE IF EXISTS SPORT;
-- DROP TABLE IF EXISTS ATHLETE;
-- DROP TABLE IF EXISTS PAYS;

DROP TABLE `athlete`, `epreuve`, `equipe`, `est_constituer`, `match_table`, `participer_athlete`, `participer_equipe`, `pays`, `sport`;